name: buid-apache-php

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - 
       uses: actions/checkout@v2
      - 
       name: login to registry
       uses: docker/login-action@v1
       with:
          registry: ${{ secrets.REGISTRY_LABEL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: build_and_push
        run: |
          docker buildx build  --platform linux/amd64,linux/arm64,linux/arm/v7 -t ${{ secrets.REGISTRY_LABEL }}/${{ secrets.REGISTRY_IMAGE }} . --push 